### ISSUE TITLE
Does NZSL support recursion?

### ISSUE THREAD

**Issue by jarble** [NazaraEngine/ShaderLang#28]
Is it possible to define recursive functions in NZSL?

I normally use [macro expansion](https://stackoverflow.com/a/77470186/975097) to define recursive functions in shading languages, but I wish they had built-in support for recursion.

**Comment by SirLynix** [comment]
Hi.

NZSL does not prevent recursion but it is explicitly disallowed on both GLSL and SPIR-V ("The static function call graph for an entry point must not contain cycles.").

There's not much I can do about this unfortunately.

**Comment by SirLynix** [comment]
Indeed, it would be possible using this. However how should this be exposed? And since every recursive code can be turned into a loop, what would be the main advantage here?

**Comment by SirLynix** [comment]
Closed for inactivity.
