### ISSUE TITLE
Modular Features

### ISSUE THREAD

**Issue by RodrigoVieira0515** [NazaraEngine/ShaderLang#30]
Hi, i am making my own game engine and i'd like to use this for my shader system. But i'd also like to add my own dynamic features into my shaders for signaling the game engine if the shader uses transparency, fog, etc... So i'd sugest an implementation of Modular Features they could work like this:

```
[nzsl_version("1.0")]
module TextureBlit;

[feature(Fog) = False]

import VertOut, VertexShader from Engine.FullscreenVertex;

external
{
    [binding(0)] texture: sampler2D[f32]
}

struct FragOut
{
    [location(0)] color: vec4[f32]
}

[entry(frag)]
fn main(input: VertOut) -> FragOut
{
    let texColor = texture.Sample(input.uv);

    let output: FragOut;
    output.color = texColor;

    return output;
}
```

**Comment by SirLynix** [comment]
Hi, glad you find the language interesting!

I'm not sure to understand, what you suggest is a way for a shader file to expose supported (or not) features to the engine?

I still have to write documentation for the language syntax, but it does support "options", which are compile-time constants provided by the engine, allowing to tweak the produced shader.

Here's a quick example from my own game engine:
```rs
option ApproximatesRGB: bool = false;

[export]
fn LinearTosRGB(color: vec3[f32]) -> vec3[f32]
{
	const if (!ApproximatesRGB)
	{
		return select(
			color > (0.0031308).rrr,
			1.055 * pow(color, (1.0 / 2.4).rrr) - (0.055).rrr,
			12.92 * color
		);
	}
	else
		return pow(color, (1.0 / 2.2).rrr);
}
```
[(full code)](https://github.com/NazaraEngine/NazaraEngine/blob/main/src/Nazara/Graphics/Resources/Shaders/Modules/Math/Color.nzsl#L6)

This lets the engine set a boolean called `ApproximatesRGB` to either true or false (the default value being false), which is then used by a `const if` (compile-time branch) which allows to tweak generation (and can be used to make function/struct members/etc. conditional).

another example:
```rs
option HasBaseColorTexture: bool = false;

fn ComputeColor(input: VertOut) -> vec4[f32]
{
	let color = settings.BaseColor;

	const if (HasBaseColorTexture)
		color *= MaterialBaseColorMap.Sample(input.uv);

// ...

	return color;
}
```
[(full code)](https://github.com/NazaraEngine/NazaraEngine/blob/main/src/Nazara/Graphics/Resources/Shaders/BasicMaterial.nzsl)

This allows your engine to check which options are declared inside your shader file (see the [ReflectVisitor](https://github.com/NazaraEngine/ShaderLang/blob/main/include/NZSL/Ast/ReflectVisitor.hpp#L42)) and enable/disable portions of it, this is called UberShader.

**Comment by RodrigoVieira0515** [comment]
This is exacty what i wanted, thanks
