### ISSUE TITLE
Options of different types

### ISSUE THREAD

**Issue by RodrigoVieira0515** [NazaraEngine/ShaderLang#31]
Hi, i want to create an option with a custom struct instead of a primitive, the compiler doesnt give any erorrors about using a custom type but i cant initialize the option

Exception Ouput: "_(35,29 -> 75): CInvalidCast error: invalid cast to type struct a"

```
[nzsl_version("1.0")]
module;

[layout(std140)]
struct Matrices
{
	projection: mat4[f32],
	view: mat4[f32],
	model: mat4[f32]
}

external
{
	[binding(0)] matrices: uniform[Matrices]
}

struct VertIn
{
	[location(0)] pos: vec3[f32],
	[location(1)] color: vec4[f32]
}

struct VertOut
{
	[location(0)] color: vec4[f32],
	[builtin(position)] pos: vec4[f32]
}

struct a {
	projection: mat4[f32],
	view: mat4[f32],
	model: mat4[f32]
}

option ApproximatesRGB: a = a(mat4[f32](1.0),mat4[f32](1.0),mat4[f32](1.0));

[entry(vert)]
fn main(input: VertIn) -> VertOut
{
	let worldPos = matrices.model * vec4[f32](input.pos, 1.0);

	let test: a;

	let output: VertOut;
	output.pos = matrices.projection * matrices.view * worldPos;
	output.color = input.color;
	return output;
}

struct FragOut
{
	[location(0)] color: vec4[f32]
}

[entry(frag)]
fn main(input: VertOut) -> FragOut
{
	let output: FragOut;
	output.color = input.color;
	return output;
}
```

**Comment by SirLynix** [comment]
Hi.

Yes options are not meant to be something else than scalar values (primitive types or vectors), you can declare multiple options instead.

I agree this should be made an error while declaring the option and will add it.

About your example, options are compile-time values, which means they don't exist at runtime and are not part of the generated code (their purpose is to influence the generated code).

I understand it's just a silly example but projection/view/model matrices should not options.
