### ISSUE TITLE
[Feature] Add support for out and inout parameters.

### ISSUE THREAD

**Issue by SirLynix** [NazaraEngine/ShaderLang#45]
Proposed syntax:
```rs
fn half(inout vec3[f32]: color)
{
    color *= 0.5;
}

fn foo()
{
    let x = vec3[f32](1.0, 1.0, 1.0);
    half(inout x);
    // x is vec3[f32](0.5, 0.5, 0.5);
}
```

**Comment by NiiRoZz** [comment]
Should we really specify _inout_ also when calling the method? I would say it is maybe too much. And what would happen if you don't put this keyword in the function call, it would just create an error?

**Comment by SirLynix** [comment]
Yes, the idea is to know when you read the code that calling that function will change the parameter value (which can be confusing otherwise).

This is also how it's done in C# for example.
